import { View, Text } from "react-native";
import React from "react";

import styles from "./Welcome.style";

const Welcome = () => {
  return (
    <View style={styles.welcomeView}>
      <View>
        <Text style={styles.h1}>The Community Showcase</Text>
        <Text style={styles.p}>
          Browse through a collection of imaginative and visually stunning
          images generated by DALL-E AI
        </Text>
      </View>
    </View>
  );
};

export default Welcome;
